AWSTemplateFormatVersion: '2010-09-09'
Description: 'This is the template for creating a simple URL Redirection service named
  Redirector with API Gateway and  AWS Lambda

  '
Resources:
  RedirectorCreateRedirection:
    Properties:
      CodeUri: s3://url-redirector/7271bbddb12d0c61a89550e36325d11b
      Description: 'This function takes in a URL, stores it in DynamoDB with a unique
        key and returns the unique key back as a response

        '
      Environment:
        Variables:
          TABLE_NAME: Redirector-Redirections-Table
          TOKEN_SIZE: 10
      Handler: redirector.create_redirection
      Runtime: python3.6
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
