AWSTemplateFormatVersion: '2010-09-09'
Description: 'This is the template for creating a simple URL Redirection service named
  Redirector with API Gateway and  AWS Lambda

  '
Resources:
  RedirectionsTable:
    Properties:
      PrimaryKey:
        Name: id
        Type: String
    Type: AWS::Serverless::SimpleTable
  RedirectorCreateRedirection:
    Properties:
      CodeUri: s3://url-redirector/fe0acb04f5d4fbda709b8f45048d437e
      Description: 'This function takes in a URL, stores it in DynamoDB with a unique
        key and returns the unique key back as a response

        '
      Environment:
        Variables:
          TABLE_NAME:
            Ref: RedirectionsTable
          TOKEN_SIZE: 10
      Handler: redirector.create_redirection
      Policies:
      - Statement:
        - Action:
          - dynamodb:PutItem
          Effect: Allow
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:dynamodb:'
              - Ref: AWS::Region
              - ':'
              - Ref: AWS::AccountId
              - :table/
              - Ref: RedirectionsTable
        Version: '2012-10-17'
      Runtime: python3.6
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
