AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  This is the template for creating a simple URL Redirection service named Redirector with API Gateway and  AWS Lambda
Resources:
    RedirectorCreateRedirection:
        Type: AWS::Serverless::Function
        Properties:
          Handler: redirector.create_redirection
          Runtime: python3.6
          CodeUri: redirector
          Description: >
            This function takes in a URL, stores it in DynamoDB with a unique key
            and returns the unique key back as a response
          Environment:
            Variables:
              TOKEN_SIZE: 10
              TABLE_NAME:
                Ref: RedirectionsTable
          Policies:
            - Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'dynamodb:PutItem'
                  Resource:
                    'Fn::Join':
                      - ''
                      - - 'arn:aws:dynamodb:'
                        - Ref: 'AWS::Region'
                        - ':'
                        - Ref: 'AWS::AccountId'
                        - ':table/'
                        - Ref: RedirectionsTable
          Events:
            SubmitUrl:
              Type: Api
              Properties:
                Path: /submit
                Method: post

    RedirectorRedirect:
        Type: AWS::Serverless::Function
        Properties:
          Handler: redirector.redirect
          Runtime: python3.6
          CodeUri: redirector
          Description: >
            This function takes a unique key, finds the url that
            is in the DynamoDB for that key and creates a 301 redirection
          Environment:
            Variables:
              TABLE_NAME:
                Ref: RedirectionsTable
          Policies:
            - Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - 'dynamodb:GetItem'
                  Resource:
                    'Fn::Join':
                      - ''
                      - - 'arn:aws:dynamodb:'
                        - Ref: 'AWS::Region'
                        - ':'
                        - Ref: 'AWS::AccountId'
                        - ':table/'
                        - Ref: RedirectionsTable
          Events:
            ProxyApiGreedy:
              Type: Api
              Properties:
                Path: /{url+}
                Method: ANY

    RedirectionsTable:
      Type: AWS::Serverless::SimpleTable
      Properties:
        PrimaryKey:
          Name: id
          Type: String
